"""add monime payments webhook logs and bank providers

Revision ID: 8eef02a04421
Revises: 258719ae9290
Create Date: 2026-04-22 09:03:34.678782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '8eef02a04421'
down_revision: Union[str, None] = '258719ae9290'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('replied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replied_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_submissions_id'), 'contact_submissions', ['id'], unique=False)
    op.create_index(op.f('ix_contact_submissions_ticket_id'), 'contact_submissions', ['ticket_id'], unique=True)

    op.create_table('monime_bank_providers',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=10), nullable=True),
    sa.Column('provider_type', sa.String(length=50), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('supported_currencies', sa.JSON(), nullable=True),
    sa.Column('requires_account_number', sa.Boolean(), nullable=True),
    sa.Column('requires_branch_code', sa.Boolean(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('cached_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_table('monime_webhook_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.String(length=100), nullable=True),
    sa.Column('event_name', sa.String(length=100), nullable=False),
    sa.Column('object_type', sa.String(length=50), nullable=True),
    sa.Column('object_id', sa.String(length=100), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('signature', sa.String(length=255), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=True),
    sa.Column('processing_result', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monime_webhook_logs_event_id'), 'monime_webhook_logs', ['event_id'], unique=False)
    op.create_index(op.f('ix_monime_webhook_logs_event_name'), 'monime_webhook_logs', ['event_name'], unique=False)
    op.create_index(op.f('ix_monime_webhook_logs_id'), 'monime_webhook_logs', ['id'], unique=False)
    op.create_index(op.f('ix_monime_webhook_logs_object_id'), 'monime_webhook_logs', ['object_id'], unique=False)

    op.create_table('monime_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('monime_payment_id', sa.String(length=100), nullable=True),
    sa.Column('payment_type', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('amount_value', sa.Integer(), nullable=True),
    sa.Column('source_account_id', sa.String(length=100), nullable=True),
    sa.Column('destination_type', sa.String(length=50), nullable=True),
    sa.Column('destination_provider_id', sa.String(length=50), nullable=True),
    sa.Column('destination_phone', sa.String(length=20), nullable=True),
    sa.Column('destination_account', sa.String(length=100), nullable=True),
    sa.Column('fees', sa.JSON(), nullable=True),
    sa.Column('failure_code', sa.String(length=50), nullable=True),
    sa.Column('failure_message', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('raw_response', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monime_payments_id'), 'monime_payments', ['id'], unique=False)
    op.create_index(op.f('ix_monime_payments_monime_payment_id'), 'monime_payments', ['monime_payment_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_monime_payments_monime_payment_id'), table_name='monime_payments')
    op.drop_index(op.f('ix_monime_payments_id'), table_name='monime_payments')
    op.drop_table('monime_payments')
    op.drop_index(op.f('ix_monime_webhook_logs_object_id'), table_name='monime_webhook_logs')
    op.drop_index(op.f('ix_monime_webhook_logs_id'), table_name='monime_webhook_logs')
    op.drop_index(op.f('ix_monime_webhook_logs_event_name'), table_name='monime_webhook_logs')
    op.drop_index(op.f('ix_monime_webhook_logs_event_id'), table_name='monime_webhook_logs')
    op.drop_table('monime_webhook_logs')
    op.drop_table('monime_bank_providers')
    op.drop_index(op.f('ix_contact_submissions_ticket_id'), table_name='contact_submissions')
    op.drop_index(op.f('ix_contact_submissions_id'), table_name='contact_submissions')
    op.drop_table('contact_submissions')
    # ### end Alembic commands ###
