"""Add idempotency key and webhook verification fields

Revision ID: a10f3b388ca9
Revises: 1c66a38847df
Create Date: 2026-03-26 18:41:08.457169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a10f3b388ca9'
down_revision: Union[str, None] = '1c66a38847df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('idempotency_key', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_orders_idempotency_key'), 'orders', ['idempotency_key'], unique=True)
    op.add_column('yoopay_payments', sa.Column('webhook_signature', sa.String(length=255), nullable=True))
    op.add_column('yoopay_payments', sa.Column('webhook_verified', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('yoopay_payments', 'webhook_verified')
    op.drop_column('yoopay_payments', 'webhook_signature')
    op.drop_index(op.f('ix_orders_idempotency_key'), table_name='orders')
    op.drop_column('orders', 'idempotency_key')
    # ### end Alembic commands ###
